#!/usr/bin/env bash
# Get info from about a subdomain

display_info() {
	local domain="$1"
	local subdomain="$2"
	
	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
		for sub in "${subdomains[@]}"; do
			display_info "$domain" "$sub"
		done
	else
		record_type=$(dig +short -t A "$subdomain.$domain" | awk '{print "A record"}')
		destination=$(dig +short -t A "$subdomain.$domain")

		echo "The subdomain $subdomain is a $record_type and points to $destination"
	fi
}
if [ "$#" -eq 2 ]; then
	display_info "$1" "$2"
else
	display_info "$1"
fi
