#!/usr/bin/env bash
# Download and confiure a web server

# Update package list
sudo apt-get update

# Install Nginx
sudo apt -y install nginx

# Start Nginx
sudo service nginx start

# Create a simple HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx
printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default
 
# Reload Nginx
sudo service nginx reload
