#!/usr/bin/env bash
# Download and confiure a web server

# Update package list
sudo apt-get update

# Install Nginx
sudo apt -y install nginx

# Start Nginx
sudo service nginx start

# Create a simple HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx
sudo sed -i 's/80 default_server;/a \\tlocation /redirect_me {\n\t\return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
 
# Reload Nginx
sudo service ngix reload
