#!/usr/bin/env bash
# Update package list
sudo apt-get update

# Install haproxy
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*

#Configure the config file
printf '%s\n' "frontend web
	bind *:80
	default_backend myservers

backend myservers
	balance roundrobin
	server web-01 3.84.158.65:80
	server web-02 3.90.85.11:80
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Reload the server
sudo service haproxy reload
