#!/usr/bin/env bash
# Display lines from 1 to 20 with strings in between
i=1
while [ $i -le 20 ]; do
	case $i in
		5) 
			echo "bad luck from China"
			;;
		10)
			echo "bad luck from Japan"
			;;
		18)
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
