#!/usr/bin/env bash
# Display time 12 hours 59 mins
mins=1
hour=0
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	while [ $mins -le 59 ]; do
		echo "$mins"
		((mins++))
	done
	mins=1
	((hour++))
done
