#!/usr/bin/env bash
# Change the Ip addresses for localhost and facebook.com

sudo cp /etc/hosts ~/hosts.new && sudo sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new && sudo cp ~/hosts.new /etc/hosts && rm ~/hosts.new

echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts > /dev/null
